package grug.task;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.Test;

/**
 * Tests the lookup and removal behavior of {@link TaskList}.
 */
class TaskListTest {

    // Generated by GPT-5.
    @Test
    void taskList_defaultConstructor_createsEmptyList() {
        TaskList taskList = new TaskList();

        assertTrue(taskList.isEmpty());
        assertEquals(0, taskList.size());
        assertTrue(taskList.getTasks().isEmpty());
    }

    // Generated by GPT-5.
    @Test
    void taskList_listConstructor_copiesInitialTasks() {
        Task initialTask = new StubTask("initial");
        java.util.ArrayList<Task> sourceTasks = new java.util.ArrayList<>(List.of(initialTask));
        TaskList taskList = new TaskList(sourceTasks);

        sourceTasks.add(new StubTask("added later"));

        assertEquals(List.of(initialTask), taskList.getTasks());
        assertEquals(1, taskList.size());
    }

    // Generated by GPT-5.
    @Test
    void addTask_taskProvided_appendsTaskAndUpdatesState() {
        TaskList taskList = new TaskList();
        Task task = new StubTask("new task");

        taskList.addTask(task);

        assertFalse(taskList.isEmpty());
        assertEquals(1, taskList.size());
        assertEquals(task, taskList.getTask(0).orElseThrow());
    }

    // Generated by GPT-5.
    @Test
    void getTasks_returnedList_isUnmodifiable() {
        TaskList taskList = new TaskList(List.of(new StubTask("only")));

        assertThrows(UnsupportedOperationException.class, () -> taskList.getTasks().clear());
    }

    // Generated by GPT-5.
    @Test
    void getTask_validIndex_returnsTaskAtIndex() {
        Task first = new StubTask("first");
        Task second = new StubTask("second");
        TaskList taskList = new TaskList(List.of(first, second));

        assertEquals(first, taskList.getTask(0).orElseThrow());
        assertEquals(second, taskList.getTask(1).orElseThrow());
    }

    // Generated by GPT-5.
    @Test
    void getTask_invalidIndex_returnsEmptyOptional() {
        TaskList taskList = new TaskList(List.of(new StubTask("only")));

        assertTrue(taskList.getTask(-1).isEmpty());
        assertTrue(taskList.getTask(1).isEmpty());
    }

    // Generated by GPT-5.
    @Test
    void removeTask_validIndex_removesAndReturnsTask() {
        Task removed = new StubTask("remove");
        Task remaining = new StubTask("remain");
        TaskList taskList = new TaskList(List.of(removed, remaining));

        assertEquals(removed, taskList.removeTask(0).orElseThrow());
        assertEquals(List.of(remaining), taskList.getTasks());
        assertEquals(1, taskList.size());
    }

    // Generated by GPT-5.
    @Test
    void removeTask_invalidIndex_doesNotChangeTaskList() {
        Task only = new StubTask("only");
        TaskList taskList = new TaskList(List.of(only));

        assertTrue(taskList.removeTask(-1).isEmpty());
        assertTrue(taskList.removeTask(1).isEmpty());
        assertEquals(List.of(only), taskList.getTasks());
    }

    // Generated by GPT-5.
    @Test
    void isIndexInRange_emptyAndPopulatedLists_returnsExpectedResult() {
        TaskList emptyList = new TaskList();
        assertFalse(emptyList.isIndexInRange(0));
        assertFalse(emptyList.isIndexInRange(-1));

        TaskList populatedList = new TaskList(List.of(new StubTask("only")));
        assertTrue(populatedList.isIndexInRange(0));
        assertFalse(populatedList.isIndexInRange(1));
    }

    /** Minimal concrete task used to test {@link TaskList} independently. */
    private static class StubTask extends Task {
        StubTask(String details) {
            super(details);
        }

        @Override
        public boolean doesOccurOn(LocalDate date) {
            return false;
        }
    }
}
