package grug.task;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;

/** Tests common task state and task-specific date behavior. */
class TaskTest {

    // Generated by GPT-5.
    @Test
    void task_newTask_startsIncompleteAndExposesDetails() {
        TodoTask task = new TodoTask("read book");

        assertEquals("read book", task.getDetails());
        assertFalse(task.isCompleted());
    }

    // Generated by GPT-5.
    @Test
    void markCompleteAndIncomplete_togglesCompletionState() {
        TodoTask task = new TodoTask("task");

        task.markComplete();
        assertTrue(task.isCompleted());
        task.markIncomplete();
        assertFalse(task.isCompleted());
    }

    // Generated by GPT-5.
    @Test
    void todoTask_doesOccurOn_alwaysReturnsFalse() {
        assertFalse(new TodoTask("task").doesOccurOn(LocalDate.of(2026, 1, 1)));
    }

    // Generated by GPT-5.
    @Test
    void taskToString_incompleteAndComplete_containsCompletionMarker() {
        TodoTask task = new TodoTask("task");

        assertEquals("[T][ ][MED] task", task.toString());
        task.markComplete();
        assertEquals("[T][X][MED] task", task.toString());
    }

    // Generated by GPT-5.
    @Test
    void deadlineTask_doesOccurOn_matchesDeadlineDateOnly() {
        DeadlineTask task = new DeadlineTask("submit", "2026-12-25 17:00");

        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 25)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 24)));
    }

    // Generated by GPT-5.
    @Test
    void eventTask_doesOccurOn_matchesInclusiveDateRange() {
        EventTask task = new EventTask("meeting", "2026-12-25 10:00", "2026-12-27 11:00");

        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 25)));
        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 26)));
        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 27)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 24)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 28)));
    }

    @Test
    void eventTask_startAfterEnd_throwsIllegalArgumentException() {
        assertThrows(IllegalArgumentException.class, () -> {
            new EventTask("(invalid) start AFTER end", "12-25", "12-24");
        });
    }

    @Test
    void eventTask_startEqualsEnd_doesNotThrow() {
        assertDoesNotThrow(() -> new EventTask("start == end", "2000-12-25", "2000-12-25"));
    }

    @Test
    void eventTask_doesOccurOn_startEqualsEnd() {
        EventTask eventTask = new EventTask("start == end", "2000-12-25", "2000-12-25");
        assertTrue(eventTask.doesOccurOn(LocalDate.of(2000, 12, 25)));
        assertFalse(eventTask.doesOccurOn(LocalDate.of(2000, 12, 24)));
        assertFalse(eventTask.doesOccurOn(LocalDate.of(2000, 12, 26)));
        assertFalse(eventTask.doesOccurOn(LocalDate.of(1999, 12, 25)));
    }
}
