package grug.task;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;

/** Tests common task state and task-specific date behavior. */
class TaskTest {

    // Generated by GPT-5.
    @Test
    void task_newTask_startsIncompleteAndExposesDetails() {
        TodoTask task = new TodoTask("read book");

        assertEquals("read book", task.getDetails());
        assertFalse(task.getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void markCompleteAndIncomplete_togglesCompletionState() {
        TodoTask task = new TodoTask("task");

        task.markComplete();
        assertTrue(task.getCompleted());
        task.markIncomplete();
        assertFalse(task.getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void todoTask_doesOccurOn_alwaysReturnsFalse() {
        assertFalse(new TodoTask("task").doesOccurOn(LocalDate.of(2026, 1, 1)));
    }

    // Generated by GPT-5.
    @Test
    void taskToString_incompleteAndComplete_containsCompletionMarker() {
        TodoTask task = new TodoTask("task");

        assertEquals("[T][ ] task", task.toString());
        task.markComplete();
        assertEquals("[T][X] task", task.toString());
    }

    // Generated by GPT-5.
    @Test
    void deadlineTask_doesOccurOn_matchesDeadlineDateOnly() {
        DeadlineTask task = new DeadlineTask("submit", "2026-12-25 17:00");

        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 25)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 24)));
    }

    // Generated by GPT-5.
    @Test
    void eventTask_doesOccurOn_matchesInclusiveDateRange() {
        EventTask task = new EventTask("meeting", "2026-12-25 10:00", "2026-12-27 11:00");

        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 25)));
        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 26)));
        assertTrue(task.doesOccurOn(LocalDate.of(2026, 12, 27)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 24)));
        assertFalse(task.doesOccurOn(LocalDate.of(2026, 12, 28)));
    }
}
