package grug.command;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;

/** Tests conversion of user input into typed commands. */
class CommandParserTest {
    @Test
    void parseInput_findOnCommand_returnsExpectedCommands() throws Exception {
        // previous year, instead of current year
        assertInstanceOf(GrugCommand.FindTasksByDateCommand.class, CommandParser.parseInput("find-on 2025-09-09"));
        // no year, instead of current year
        assertInstanceOf(GrugCommand.FindTasksByDateCommand.class, CommandParser.parseInput("find-on 09-09"));
    }

    @Test
    void parseInput_findCommands_returnsExpectedCommands() throws Exception {
        assertInstanceOf(GrugCommand.FindTasksByDetailsCommand.class, CommandParser.parseInput("find a"));
        assertInstanceOf(GrugCommand.FindTasksByDetailsCommand.class, CommandParser.parseInput("find a b"));
        assertInstanceOf(GrugCommand.FindTasksByDetailsCommand.class, CommandParser.parseInput("find  a  b "));
    }

    @Test
    void parseInput_findCommands_parsesDetails() throws Exception {
        GrugCommand.FindTasksByDetailsCommand findWithSpaces = assertInstanceOf(
                GrugCommand.FindTasksByDetailsCommand.class,
                CommandParser.parseInput("find  a  b  "));
        assertEquals(findWithSpaces.detailsSubstring(), "a b");

        GrugCommand.FindTasksByDetailsCommand findWithNewlines = assertInstanceOf(
                GrugCommand.FindTasksByDetailsCommand.class,
                CommandParser.parseInput("\tfind a\r\nb\n"));
        assertEquals(findWithNewlines.detailsSubstring(), "a b");
    }

    // Generated by GPT-5.
    @Test
    void parseInput_blankAndSimpleCommands_returnsExpectedCommands() throws Exception {
        assertInstanceOf(GrugCommand.EmptyCommand.class, CommandParser.parseInput("  "));
        assertInstanceOf(GrugCommand.QuitCommand.class, CommandParser.parseInput("BYE"));
        assertInstanceOf(GrugCommand.ListTasksCommand.class, CommandParser.parseInput("list"));
    }

    // Generated by GPT-5.
    @Test
    void parseInput_taskCommands_parsesDetailsAndDates() throws Exception {
        GrugCommand.AddTodoTaskCommand todo = assertInstanceOf(GrugCommand.AddTodoTaskCommand.class,
                CommandParser.parseInput("todo buy milk"));
        GrugCommand.AddDeadlineTaskCommand deadline = assertInstanceOf(GrugCommand.AddDeadlineTaskCommand.class,
                CommandParser.parseInput("deadline submit /by 2026-12-25 17:00"));
        GrugCommand.AddEventTaskCommand event = assertInstanceOf(GrugCommand.AddEventTaskCommand.class,
                CommandParser.parseInput("event meeting /from 2026-12-25 10:00 /to 2026-12-25 11:00"));

        assertEquals("buy milk", todo.task().getDetails());
        assertEquals("2026-12-25 17:00", deadline.task().getDeadlineDatetime().toString().replace('T', ' '));
        assertEquals("2026-12-25 10:00", event.task().getStartDatetime().toString().replace('T', ' '));
    }

    // Generated by GPT-5.
    @Test
    void parseInput_indexAndDateCommands_parsesArguments() throws Exception {
        GrugCommand.MarkTaskCommand mark = assertInstanceOf(GrugCommand.MarkTaskCommand.class,
                CommandParser.parseInput("mark 2"));
        GrugCommand.UnmarkTaskCommand unmark = assertInstanceOf(GrugCommand.UnmarkTaskCommand.class,
                CommandParser.parseInput("unmark 3"));
        GrugCommand.DeleteTaskCommand delete = assertInstanceOf(GrugCommand.DeleteTaskCommand.class,
                CommandParser.parseInput("delete 4"));
        GrugCommand.FindTasksByDateCommand find = assertInstanceOf(GrugCommand.FindTasksByDateCommand.class,
                CommandParser.parseInput("find-on 2026-12-25"));

        assertEquals(2, mark.taskNum());
        assertEquals(3, unmark.taskNum());
        assertEquals(4, delete.taskNum());
        assertEquals(LocalDate.of(2026, 12, 25), find.date());
    }

    // Generated by GPT-5.
    @Test
    void parseInput_invalidCommands_throwsDescriptiveParserException() {
        assertThrows(GrugCommandParserException.UnknownCommand.class, () -> CommandParser.parseInput("unknown"));
        assertThrows(GrugCommandParserException.InvalidUsage.class, () -> CommandParser.parseInput(
                "todo"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "mark not-a-number"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "deadline submit /by invalid-date"));
        assertThrows(GrugCommandParserException.class, () -> CommandParser.parseInput("find"));
    }
}
