package grug.command;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;

/** Tests conversion of user input into typed commands. */
class CommandParserTest {
    @Test
    void parseInput_findOnCommand_returnsExpectedCommands() throws Exception {
        // previous year, instead of current year
        assertInstanceOf(GrugCommand.FindTasksByDate.class, CommandParser.parseInput("find-on 2025-09-09"));
        // no year, instead of current year
        assertInstanceOf(GrugCommand.FindTasksByDate.class, CommandParser.parseInput("find-on 09-09"));
    }

    // Generated by GPT-5.
    @Test
    void parseInput_blankAndSimpleCommands_returnsExpectedCommands() throws Exception {
        assertInstanceOf(GrugCommand.Empty.class, CommandParser.parseInput("  "));
        assertInstanceOf(GrugCommand.Quit.class, CommandParser.parseInput("BYE"));
        assertInstanceOf(GrugCommand.ListTasks.class, CommandParser.parseInput("list"));
    }

    // Generated by GPT-5.
    @Test
    void parseInput_taskCommands_parsesDetailsAndDates() throws Exception {
        GrugCommand.AddTodoTask todo = assertInstanceOf(GrugCommand.AddTodoTask.class,
                CommandParser.parseInput("todo buy milk"));
        GrugCommand.AddDeadlineTask deadline = assertInstanceOf(GrugCommand.AddDeadlineTask.class,
                CommandParser.parseInput("deadline submit /by 2026-12-25 17:00"));
        GrugCommand.AddEventTask event = assertInstanceOf(GrugCommand.AddEventTask.class,
                CommandParser.parseInput("event meeting /from 2026-12-25 10:00 /to 2026-12-25 11:00"));

        assertEquals("buy milk", todo.task().getDetails());
        assertEquals("2026-12-25 17:00", deadline.task().getDeadlineDatetime().toString().replace('T', ' '));
        assertEquals("2026-12-25 10:00", event.task().getStartDatetime().toString().replace('T', ' '));
    }

    // Generated by GPT-5.
    @Test
    void parseInput_indexAndDateCommands_parsesArguments() throws Exception {
        GrugCommand.MarkTask mark = assertInstanceOf(GrugCommand.MarkTask.class,
                CommandParser.parseInput("mark 2"));
        GrugCommand.UnmarkTask unmark = assertInstanceOf(GrugCommand.UnmarkTask.class,
                CommandParser.parseInput("unmark 3"));
        GrugCommand.DeleteTask delete = assertInstanceOf(GrugCommand.DeleteTask.class,
                CommandParser.parseInput("delete 4"));
        GrugCommand.FindTasksByDate find = assertInstanceOf(GrugCommand.FindTasksByDate.class,
                CommandParser.parseInput("find-on 2026-12-25"));

        assertEquals(2, mark.taskNum());
        assertEquals(3, unmark.taskNum());
        assertEquals(4, delete.taskNum());
        assertEquals(LocalDate.of(2026, 12, 25), find.date());
    }

    // Generated by GPT-5.
    @Test
    void parseInput_invalidCommands_throwsDescriptiveParserException() {
        assertThrows(GrugCommandParserException.UnknownCommand.class, () -> CommandParser.parseInput("unknown"));
        assertThrows(GrugCommandParserException.InvalidUsage.class, () -> CommandParser.parseInput(
                "todo"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "mark not-a-number"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "deadline submit /by invalid-date"));
    }
}
