package grug.command;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;
import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import grug.storage.TaskStorage;
import grug.task.DeadlineTask;
import grug.task.EventTask;
import grug.task.Task;
import grug.task.TaskList;
import grug.task.TodoTask;

/** Tests execution of every concrete {@link GrugCommand}. */
class GrugCommandTest {

    @TempDir
    Path temporaryDirectory;

    private TaskStorage createTempStorage() {
        return new TaskStorage(temporaryDirectory.resolve("tasks.txt").toString());
    }

    // Generated by GPT-5.
    @Test
    void emptyAndQuit_execute_returnsExpectedControlResults() {
        TaskStorage storage = createTempStorage();

        CommandResult empty = new GrugCommand.EmptyCommand().execute(new TaskList(), storage);
        CommandResult quit = new GrugCommand.QuitCommand().execute(new TaskList(), storage);

        assertEquals(new CommandResult.Ok("", false), empty);
        assertEquals(new CommandResult.Ok("Unga. Bye. さよなら", true), quit);
    }

    // Generated by GPT-5.
    @Test
    void listTasks_execute_reportsEmptyAndPopulatedLists() {
        TaskStorage storage = createTempStorage();
        TaskList emptyTasks = new TaskList();
        TaskList populatedTasks = new TaskList(List.of(new TodoTask("buy milk")));

        assertEquals(new CommandResult.Ok("No tasks added.", false),
                new GrugCommand.ListTasksCommand().execute(emptyTasks, storage));
        assertEquals(new CommandResult.Ok("1. [T][ ] buy milk", false),
                new GrugCommand.ListTasksCommand().execute(populatedTasks, storage));
    }

    // Generated by GPT-5.
    @Test
    void addTaskCommands_execute_addsTasksAndPersistsThem() throws Exception {
        TaskList tasks = new TaskList();
        TaskStorage storage = createTempStorage();

        CommandResult todoResult = new GrugCommand.AddTodoTaskCommand(new TodoTask("todo")).execute(tasks, storage);
        CommandResult deadlineResult = new GrugCommand.AddDeadlineTaskCommand(
                new DeadlineTask("deadline", "2026-12-25 17:00")).execute(tasks, storage);
        CommandResult eventResult = new GrugCommand.AddEventTaskCommand(
                new EventTask("event", "2026-12-25 10:00", "2026-12-25 11:00")).execute(tasks, storage);

        assertInstanceOf(CommandResult.Ok.class, todoResult);
        assertInstanceOf(CommandResult.Ok.class, deadlineResult);
        assertInstanceOf(CommandResult.Ok.class, eventResult);
        assertEquals(3, tasks.getSize());
        assertEquals(3, storage.loadTasks().size());
    }

    // Generated by GPT-5.
    @Test
    void markAndUnmarkTask_execute_updatesCompletionState() throws Exception {
        Task task = new TodoTask("task");
        TaskList tasks = new TaskList(List.of(task));
        TaskStorage storage = createTempStorage();

        CommandResult markResult = new GrugCommand.MarkTaskCommand(1).execute(tasks, storage);
        assertInstanceOf(CommandResult.Ok.class, markResult);
        assertTrue(task.isCompleted());

        CommandResult unmarkResult = new GrugCommand.UnmarkTaskCommand(1).execute(tasks, storage);
        assertInstanceOf(CommandResult.Ok.class, unmarkResult);
        assertFalse(task.isCompleted());
    }

    // Generated by GPT-5.
    @Test
    void markUnmarkAndDeleteTask_invalidNumber_returnsErrorWithoutMutation() {
        TaskList tasks = new TaskList(List.of(new TodoTask("task")));
        TaskStorage storage = createTempStorage();

        assertEquals(new CommandResult.Err("Can't find task number 0", false),
                new GrugCommand.MarkTaskCommand(0).execute(tasks, storage));
        assertEquals(new CommandResult.Err("Can't find task number 0", false),
                new GrugCommand.UnmarkTaskCommand(0).execute(tasks, storage));
        assertEquals(new CommandResult.Err("Can't find task number 2", false),
                new GrugCommand.DeleteTaskCommand(2).execute(tasks, storage));
        assertEquals(1, tasks.getSize());
        assertFalse(tasks.getTask(0).orElseThrow().isCompleted());
    }

    // Generated by GPT-5.
    @Test
    void deleteTask_execute_removesAndPersistsRemovedTask() throws Exception {
        TaskList tasks = new TaskList(List.of(new TodoTask("first"), new TodoTask("second")));
        TaskStorage storage = createTempStorage();

        CommandResult result = new GrugCommand.DeleteTaskCommand(1).execute(tasks, storage);

        assertInstanceOf(CommandResult.Ok.class, result);
        assertEquals(1, tasks.getSize());
        assertEquals("second", tasks.getTask(0).orElseThrow().getDetails());
        assertEquals("second", storage.loadTasks().get(0).getDetails());
    }

    // Generated by GPT-5.
    @Test
    void findTasksByDate_execute_returnsOnlyTasksOccurringOnDate() {
        TaskList tasks = new TaskList(List.of(
                new TodoTask("todo"),
                new DeadlineTask("deadline", "2026-12-25 17:00"),
                new EventTask("event", "2026-12-24 10:00", "2026-12-26 11:00")));

        CommandResult result = new GrugCommand.FindTasksByDateCommand(LocalDate.of(2026, 12, 25))
                .execute(tasks, createTempStorage());

        assertEquals(new CommandResult.Ok(
                "2. [D][ ] deadline (by: Dec 25 2026 1700)\n"
                        + "3. [E][ ] event (from: Dec 24 2026 1000 | to: Dec 26 2026 1100)",
                false), result);
    }

    @Test
    void findTasksByDetails_execute_returnsOnlyTasksContainingDetails() {
        TaskList tasks = new TaskList(List.of(
                new TodoTask("read book"),
                new DeadlineTask("pead boop", "2026-12-25 17:00"),
                new EventTask("eat poop", "2026-12-24 10:00", "2026-12-26 11:00")));

        CommandResult actualResult = new GrugCommand.FindTasksByDetailsCommand("ead boo").execute(tasks,
                createTempStorage());
        CommandResult expectedResult = new CommandResult.Ok(
                "1. [T][ ] read book\n" + "2. [D][ ] pead boop (by: Dec 25 2026 1700)",
                false);
        assertEquals(actualResult, expectedResult);
    }

    @Test
    void findTasksByDetails_extraWhitespaceThenExecute_ignoresExtraWhitespace() {
        TaskList tasks = new TaskList(List.of(
                new TodoTask("read book"),
                new DeadlineTask("pead boop", "2026-12-25 17:00"),
                new EventTask("eat poop", "2026-12-24 10:00", "2026-12-26 11:00")));

        CommandResult actualResult = new GrugCommand.FindTasksByDetailsCommand(" \t ead  \n  \r\n boo\r")
                .execute(tasks, createTempStorage());
        CommandResult expectedResult = new CommandResult.Ok(
                "1. [T][ ] read book\n" + "2. [D][ ] pead boop (by: Dec 25 2026 1700)",
                false);
        assertEquals(actualResult, expectedResult);
    }
}
