package grug.command;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Path;
import java.time.LocalDate;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import grug.storage.TaskStorage;
import grug.task.DeadlineTask;
import grug.task.EventTask;
import grug.task.Task;
import grug.task.TaskList;
import grug.task.TodoTask;

/** Tests execution of every concrete {@link GrugCommand}. */
class GrugCommandTest {

    @TempDir
    Path temporaryDirectory;

    private TaskStorage storage() {
        return new TaskStorage(temporaryDirectory.resolve("tasks.txt").toString());
    }

    // Generated by GPT-5.
    @Test
    void emptyAndQuit_execute_returnsExpectedControlResults() {
        TaskStorage storage = storage();

        CommandResult empty = new GrugCommand.Empty().execute(new TaskList(), storage);
        CommandResult quit = new GrugCommand.Quit().execute(new TaskList(), storage);

        assertEquals(new CommandResult.Ok("", false), empty);
        assertEquals(new CommandResult.Ok("Unga. Bye. さよなら", true), quit);
    }

    // Generated by GPT-5.
    @Test
    void listTasks_execute_reportsEmptyAndPopulatedLists() {
        TaskStorage storage = storage();
        TaskList emptyTasks = new TaskList();
        TaskList populatedTasks = new TaskList(List.of(new TodoTask("buy milk")));

        assertEquals(new CommandResult.Ok("No tasks added.", false),
                new GrugCommand.ListTasks().execute(emptyTasks, storage));
        assertEquals(new CommandResult.Ok("1. [T][ ] buy milk", false),
                new GrugCommand.ListTasks().execute(populatedTasks, storage));
    }

    // Generated by GPT-5.
    @Test
    void addTaskCommands_execute_addsTasksAndPersistsThem() throws Exception {
        TaskList tasks = new TaskList();
        TaskStorage storage = storage();

        CommandResult todoResult = new GrugCommand.AddTodoTask(new TodoTask("todo")).execute(tasks, storage);
        CommandResult deadlineResult = new GrugCommand.AddDeadlineTask(
                new DeadlineTask("deadline", "2026-12-25 17:00")).execute(tasks, storage);
        CommandResult eventResult = new GrugCommand.AddEventTask(
                new EventTask("event", "2026-12-25 10:00", "2026-12-25 11:00")).execute(tasks, storage);

        assertInstanceOf(CommandResult.Ok.class, todoResult);
        assertInstanceOf(CommandResult.Ok.class, deadlineResult);
        assertInstanceOf(CommandResult.Ok.class, eventResult);
        assertEquals(3, tasks.size());
        assertEquals(3, storage.loadTasks().size());
    }

    // Generated by GPT-5.
    @Test
    void markAndUnmarkTask_execute_updatesCompletionState() throws Exception {
        Task task = new TodoTask("task");
        TaskList tasks = new TaskList(List.of(task));
        TaskStorage storage = storage();

        CommandResult markResult = new GrugCommand.MarkTask(1).execute(tasks, storage);
        assertInstanceOf(CommandResult.Ok.class, markResult);
        assertTrue(task.getCompleted());

        CommandResult unmarkResult = new GrugCommand.UnmarkTask(1).execute(tasks, storage);
        assertInstanceOf(CommandResult.Ok.class, unmarkResult);
        assertFalse(task.getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void markUnmarkAndDeleteTask_invalidNumber_returnsErrorWithoutMutation() {
        TaskList tasks = new TaskList(List.of(new TodoTask("task")));
        TaskStorage storage = storage();

        assertEquals(new CommandResult.Err("Can't find task number 0", false),
                new GrugCommand.MarkTask(0).execute(tasks, storage));
        assertEquals(new CommandResult.Err("Can't find task number 0", false),
                new GrugCommand.UnmarkTask(0).execute(tasks, storage));
        assertEquals(new CommandResult.Err("Can't find task number 2", false),
                new GrugCommand.DeleteTask(2).execute(tasks, storage));
        assertEquals(1, tasks.size());
        assertFalse(tasks.getTask(0).orElseThrow().getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void deleteTask_execute_removesAndPersistsRemovedTask() throws Exception {
        TaskList tasks = new TaskList(List.of(new TodoTask("first"), new TodoTask("second")));
        TaskStorage storage = storage();

        CommandResult result = new GrugCommand.DeleteTask(1).execute(tasks, storage);

        assertInstanceOf(CommandResult.Ok.class, result);
        assertEquals(1, tasks.size());
        assertEquals("second", tasks.getTask(0).orElseThrow().getDetails());
        assertEquals("second", storage.loadTasks().get(0).getDetails());
    }

    // Generated by GPT-5.
    @Test
    void findTasksByDate_execute_returnsOnlyTasksOccurringOnDate() {
        TaskList tasks = new TaskList(List.of(
                new TodoTask("todo"),
                new DeadlineTask("deadline", "2026-12-25 17:00"),
                new EventTask("event", "2026-12-24 10:00", "2026-12-26 11:00")));

        CommandResult result = new GrugCommand.FindTasksByDate(LocalDate.of(2026, 12, 25))
                .execute(tasks, storage());

        assertEquals(new CommandResult.Ok(
                "2. [D][ ] deadline (by: Dec 25 2026 1700)\n"
                        + "3. [E][ ] event (from: Dec 24 2026 1000 | to: Dec 26 2026 1100)",
                false), result);
    }
}
