package grug.storage.serde;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import org.junit.jupiter.api.Test;

import grug.task.DeadlineTask;
import grug.task.EventTask;
import grug.task.Task;
import grug.task.TodoTask;

/** Tests serialization of every supported task type. */
class TaskSerializerTest {

    // Generated by GPT-5.
    @Test
    void serialize_todoTask_writesTypeCompletionAndDetails() {
        TodoTask task = new TodoTask("read\nbook");

        assertEquals("[todo]\ncompleted = 0\ndetails = read\\nbook\n", TaskSerializer.serialize(task));
    }

    // Generated by GPT-5.
    @Test
    void serialize_deadlineAndEventTasks_writesDateProperties() {
        DeadlineTask deadline = new DeadlineTask("submit", "2026-12-25 17:00");
        EventTask event = new EventTask("meeting", "2026-12-25 10:00", "2026-12-25 11:00");

        assertEquals("[deadline]\ncompleted = 0\ndetails = submit\nby = 2026-12-25 17:00\n",
                TaskSerializer.serialize(deadline));
        assertEquals("[event]\ncompleted = 0\ndetails = meeting\nstart = 2026-12-25 10:00\nend = 2026-12-25 11:00\n",
                TaskSerializer.serialize(event));
    }

    // Generated by GPT-5.
    @Test
    void serialize_unsupportedTask_throwsUnsupportedOperationException() {
        Task unsupported = new Task("task") {
            @Override
            public boolean doesOccurOn(java.time.LocalDate date) {
                return false;
            }
        };

        assertThrows(UnsupportedOperationException.class, () -> TaskSerializer.serialize(unsupported));
    }
}
