package grug.storage.serde;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.LocalDateTime;
import java.util.List;

import org.junit.jupiter.api.Test;

import grug.task.DeadlineTask;
import grug.task.EventTask;
import grug.task.Task;
import grug.task.TodoTask;

/** Tests deserialization of task data and its validation rules. */
class TaskDeserializerTest {
    // Generated by GPT-5.
    @Test
    void deserializeOne_todoWithCompletion_reconstructsTask() throws Exception {
        Task task = TaskDeserializer.deserializeOne("""
                [todo]
                completed = 1
                details = read\\nbook
                """);

        TodoTask todo = assertInstanceOf(TodoTask.class, task);
        assertEquals("read\nbook", todo.getDetails());
        assertTrue(todo.getCompleted());
    }

    @Test
    void deserializeOne_ignoresTrailingWhitespace_reconstructsTasks() throws Exception {
        Task task = TaskDeserializer.deserializeOne("""

                     [   todo ]
                   completed    = 1

                 details= read\\nbook
                """);

        TodoTask todo = assertInstanceOf(TodoTask.class, task);
        assertEquals("read\nbook", todo.getDetails());
        assertTrue(todo.getCompleted());
    }

    @Test
    void deserializeOne_malformedHeader_throwsDeserializationException() throws Exception {
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne("""
                [todo]completed = 1
                details = read\\nbook
                """));
    }

    // Generated by GPT-5.
    @Test
    void deserializeOne_deadlineAndEvent_reconstructDateTimes() throws Exception {
        DeadlineTask deadline = assertInstanceOf(DeadlineTask.class,
                TaskDeserializer.deserializeOne("[deadline]\ndetails = submit\nby = 2026-12-25 17:00"));
        EventTask event = assertInstanceOf(EventTask.class,
                TaskDeserializer.deserializeOne(
                        "[event]\ndetails = meeting\nstart = 2026-12-25 10:00\nend = 2026-12-25 11:00"));

        assertEquals(LocalDateTime.of(2026, 12, 25, 17, 0), deadline.getDeadlineDatetime());
        assertEquals(LocalDateTime.of(2026, 12, 25, 10, 0), event.getStartDatetime());
        assertEquals(LocalDateTime.of(2026, 12, 25, 11, 0), event.getEndDatetime());
        assertFalse(deadline.getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void deserializeOne_invalidInput_throwsDeserializationException() {
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne(""));
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne(
                "details = missing header"));
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne(
                "[unknown]\ndetails = task"));
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne(
                "[deadline]\ndetails = task"));
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeOne(
                "[event]\ndetails = task\nstart = invalid\nend = 2026-12-25"));
    }

    // Generated by GPT-5.
    @Test
    void deserializeMany_multipleBlocks_returnsValidTasksInOrder() throws Exception {
        String serialized = """
                [todo]
                details = first

                [todo]
                completed = 1
                details = second
                """;

        List<Task> tasks = TaskDeserializer.deserializeMany(serialized);

        assertEquals(2, tasks.size());
        assertEquals("first", tasks.get(0).getDetails());
        assertEquals("second", tasks.get(1).getDetails());
        assertTrue(tasks.get(1).getCompleted());
    }

    @Test
    void deserializeMany_multipleBlocksSomeMalformed_returnsValidTasksInOrder() throws Exception {
        // "[deadline]aaaaaaa" should count as a property, not header, since we could
        // technically form a property like [prop]aaa = value
        String serialized = """
                [todo]
                details = first

                [deadline]aaaaaaa
                completed = 1
                details = second, but still part of first
                by = 2026-12-25 00:00

                [deadline]
                completed = 1
                details = third
                by = 2026-12-25 00:00
                """;

        List<Task> tasks = TaskDeserializer.deserializeMany(serialized);

        assertEquals(1, tasks.size());
        assertEquals("third", tasks.get(0).getDetails());
        assertTrue(tasks.get(0).getCompleted());
    }

    @Test
    void deserializeMany_firstTaskMissingHeader_ignoresFirstTask() throws Exception {
        String serialized = """
                details = should skip this

                [todo]
                details = first

                [todo]
                completed = 1
                details = second
                """;

        List<Task> tasks = TaskDeserializer.deserializeMany(serialized);
        assertEquals(2, tasks.size());
        assertEquals("first", tasks.get(0).getDetails());
        assertEquals("second", tasks.get(1).getDetails());
        assertTrue(tasks.get(1).getCompleted());
    }

    // Generated by GPT-5.
    @Test
    void deserializeMany_nullInput_throwsDeserializationException() {
        assertThrows(TaskDeserializerException.class, () -> TaskDeserializer.deserializeMany(null));
    }
}
