package grug.ui;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.Optional;
import java.util.Scanner;

import org.junit.jupiter.api.Test;

/**
 * Tests input handling and control flow for the command-line user interface.
 */
class ConsoleUiTest {

    // Generated by GPT-5.
    @Test
    void readInput_inputLine_returnsStrippedInputAndDisplaysPrompt() {
        StringWriter output = new StringWriter();
        Ui ui = new ConsoleUi(new Scanner("  todo buy milk  \n"), new PrintWriter(output));

        Optional<String> input = ui.readInput("> ");

        assertEquals(Optional.of("todo buy milk"), input);
        assertEquals("> ", output.toString());
    }

    // Generated by GPT-5.
    @Test
    void readInput_endOfInput_returnsEmptyOptional() {
        StringWriter output = new StringWriter();
        Ui ui = new ConsoleUi(new Scanner(""), new PrintWriter(output));

        Optional<String> input = ui.readInput("Enter: ");

        assertEquals(Optional.empty(), input);
        assertEquals("Enter: ", output.toString());
    }
}
