package grug.ui;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Scanner;

import org.junit.jupiter.api.Test;

/**
 * Tests input handling and control flow for the command-line user interface.
 */
class UiTest {

    // Generated by GPT-5.
    @Test
    void readInput_inputLine_returnsStrippedInputAndDisplaysPrompt() {
        StringWriter output = new StringWriter();
        Ui ui = new Ui(new Scanner("  todo buy milk  \n"), new PrintWriter(output));

        Optional<String> input = ui.readInput("> ");

        assertEquals(Optional.of("todo buy milk"), input);
        assertEquals("> ", output.toString());
    }

    // Generated by GPT-5.
    @Test
    void readInput_endOfInput_returnsEmptyOptional() {
        StringWriter output = new StringWriter();
        Ui ui = new Ui(new Scanner(""), new PrintWriter(output));

        Optional<String> input = ui.readInput("Enter: ");

        assertEquals(Optional.empty(), input);
        assertEquals("Enter: ", output.toString());
    }

    // Generated by GPT-5.
    @Test
    void runReadInputLoop_callbackStopsLoop_preservesInputsAndDisplaysSeparators() {
        StringWriter output = new StringWriter();
        Ui ui = new Ui(new Scanner(" first \n second \n"), new PrintWriter(output));
        List<String> receivedInputs = new ArrayList<>();

        ui.runReadInputLoop(input -> {
            receivedInputs.add(input);
            return input.equals("second");
        });

        assertEquals(List.of("first", "second"), receivedInputs);
        String lineSeparator = System.lineSeparator();
        assertEquals("> ____________________________________________________________" + lineSeparator
                + "> ____________________________________________________________" + lineSeparator,
                output.toString());
    }

    // Generated by GPT-5.
    @Test
    void runReadInputLoop_endOfInput_stopsWithoutCallingCallbackAgain() {
        StringWriter output = new StringWriter();
        Ui ui = new Ui(new Scanner("only\n"), new PrintWriter(output));
        List<String> receivedInputs = new ArrayList<>();

        ui.runReadInputLoop(input -> {
            receivedInputs.add(input);
            return false;
        });

        assertEquals(List.of("only"), receivedInputs);
        String lineSeparator = System.lineSeparator();
        assertTrue(output.toString().endsWith("> ____________________________________________________________"
                + lineSeparator + "> "));
    }
}
