package grug.gui;

import java.io.IOException;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.scene.text.Font;

/**
 * Represents a dialog box consisting of a label containing text from the
 * speaker.
 */
public class DialogBox extends HBox {
    @FXML
    private Label dialog;

    private DialogBox(String text) {
        try {
            FXMLLoader fxmlLoader = new FXMLLoader(MainWindow.class.getResource("/view/DialogBox.fxml"));
            fxmlLoader.setController(this);
            fxmlLoader.setRoot(this);
            fxmlLoader.load();
        } catch (IOException e) {
            e.printStackTrace();
        }

        dialog.setText(text);
    }

    /**
     * Creates a {@link DialogBox} representing the user's dialog, on the right of
     * the screen.
     *
     * @param text The user's dialog text.
     * @return The {@link DialogBox} containing the user's dialog text.
     */
    public static DialogBox createFromUserDialog(String text) {
        return new DialogBox(text);
    }

    /**
     * Creates a {@link DialogBox} representing the chatbot grug's dialog, on the
     * left of the screen.
     *
     * @param response Grug's dialog text/response.
     * @return The {@link DialogBox} containing Grug's dialog text.
     */
    public static DialogBox createFromGrugDialog(String response) {
        DialogBox dialogBox = new DialogBox(response);
        dialogBox.dialog.setFont(Font.font("Monospaced"));

        dialogBox.setAlignment(Pos.TOP_LEFT);
        dialogBox.dialog.getStyleClass().add("reply-label");

        return dialogBox;
    }

    // Generated by GPT-5.
    /**
     * Creates a {@link DialogBox} that visually emphasizes an error response.
     *
     * @param response Grug's error response.
     * @return The {@link DialogBox} containing the emphasized error response.
     */
    public static DialogBox createFromErrorDialog(String response) {
        DialogBox dialogBox = createFromGrugDialog(response);
        dialogBox.dialog.getStyleClass().add("error-label");
        return dialogBox;
    }

    // Generated by GPT-5.
    /**
     * Creates a {@link DialogBox} that visually emphasizes a warning response.
     *
     * @param response Grug's warning response.
     * @return The {@link DialogBox} containing the emphasized warning response.
     */
    public static DialogBox createFromWarningDialog(String response) {
        DialogBox dialogBox = createFromGrugDialog(response);
        dialogBox.dialog.getStyleClass().add("warning-label");
        return dialogBox;
    }
}
