package task.serde;

/**
 * Represents the checked exception thrown when a serialized task cannot be
 * deserialized.
 *
 * Generated by Codex 5.6 Luna.
 */
public class TaskDeserializerException extends Exception {

    /**
     * Creates an exception with a description of the deserialization failure.
     *
     * @param message a description of the failure
     */
    public TaskDeserializerException(String message) {
        super(message);
    }

    /**
     * Creates an exception with a description and the underlying cause.
     *
     * @param message a description of the failure
     * @param cause   the underlying cause
     */
    public TaskDeserializerException(String message, Throwable cause) {
        super(message, cause);
    }
}
