package task.serde;

import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

import task.DeadlineTask;
import task.EventTask;
import task.Task;
import task.TodoTask;

/**
 * Contains static methods to deserialize tasks that were serialized and saved
 * to disk.
 */
public class TaskDeserializer {
    /**
     * Deserializes multiple task blocks from a serialized task list.
     * <p>
     * Each task block starts with a {@code [task-type]} header. Blank lines
     * between blocks are ignored, while the contents of each block are delegated
     * to {@link #deserializeOne(String)}.
     * <p>
     * Generated by Codex 5.6 Luna, then modified slightly.
     *
     * @param serializedTasks the serialized task list
     * @return the deserialized tasks, in their serialized order
     * @throws TaskDeserializerException if the input contains data before the
     *                                   first task header or if a task block is
     *                                   invalid
     */
    public static List<Task> deserializeMany(String serializedTasks) throws TaskDeserializerException {
        if (serializedTasks == null) {
            throw new TaskDeserializerException("Serialized task list cannot be null");
        }

        List<String> serializedTaskBlocks = new ArrayList<>();
        StringBuilder currentBlock = null;

        for (String line : serializedTasks.lines().toList()) {
            if (line.isBlank()) {
                continue;
            }

            String strippedLine = line.strip();
            boolean isHeader = strippedLine.matches("\\[\\s*.*?\\s*\\]");

            if (isHeader) {
                if (currentBlock != null) {
                    serializedTaskBlocks.add(currentBlock.toString());
                }
                currentBlock = new StringBuilder();
            } else if (currentBlock == null) {
                throw new TaskDeserializerException(
                        "Found task properties before the first [task-type] header");
            }

            currentBlock.append(strippedLine).append(System.lineSeparator());
        }

        if (currentBlock != null) {
            serializedTaskBlocks.add(currentBlock.toString());
        }

        List<Task> tasks = new ArrayList<>();
        for (int i = 0; i < serializedTaskBlocks.size(); i++) {
            String serializedTask = serializedTaskBlocks.get(i);
            try {
                tasks.add(deserializeOne(serializedTask));
            } catch (TaskDeserializerException e) {
                System.out.println("Skipped task %d (1-based): %s".formatted(i + 1, e.getMessage()));
            }
        }
        return tasks;
    }

    /**
     * Takes in a serialized task and converts it into its appropriate task object.
     * <p>
     *
     * ### Deserialization rules
     * The following are rules for deserialization that the serialized string must
     * follow (not task specific):
     * - The header {@code [task-type]} and properties {@code prop = value} must all
     * be on seperate lines and follow that format exactly.
     * - The header must come before all properties.
     * - Properties can be in any order.
     * - Each property occupies exactly 1 line (i.e. cannot be split into multiple
     * lines).
     * - Property names must not contain {@code [} or {@code ]} since these are
     * reserved for headers
     * - String values are not wrapped in double quotes.
     * - Line terminators may be {@code \n}, {@code \r} or {@code \r\n}
     *
     * ### Example
     *
     * <pre>
     * [todo]
     * completed = 1
     * details = run 10km
     * </pre>
     *
     * Should be converted into
     *
     * <pre>{@code
     * // TodoTask { details: "run 10km", isCompleted: true }
     * TodoTask task = new TodoTask("run 10km");
     * task.markComplete();
     * }</pre>
     *
     * @param serializedTask The serialized task data to deserialize.
     * @return The appropriate deserialized task.
     * @throws TaskDeserializerException If the serialized task data is formatted
     *                                   wrongly or is missing properties required
     *                                   by the appropriate task type.
     */
    public static Task deserializeOne(String serializedTask) throws TaskDeserializerException {
        List<String> lines = serializedTask.lines()
                .filter(line -> !line.isBlank())
                .map(line -> line.strip())
                .collect(Collectors.toList());

        if (lines.isEmpty()) {
            throw new TaskDeserializerException("Nothing to deserialize");
        }

        String header = lines.get(0);
        Pattern pattern = Pattern.compile("\\[\\s*(.*?)\\s*\\]");
        Matcher matcher = pattern.matcher(header);
        // the header must occupy the entire line. Using find() would accept a
        // task type embedded in malformed text, such as "aaa[ todo]completed=1"
        // so we use matches() instead.
        if (!matcher.matches()) {
            throw new TaskDeserializerException("Missing header [task-type]");
        }

        // guaranteed not to throw since there is exactly 1 capture group (apart from
        // the entire matching subsequence) if found
        String taskType = matcher.group(1).toLowerCase();

        HashMap<String, String> properties = new HashMap<>();

        for (int i = 1; i < lines.size(); i++) {
            String line = lines.get(i).strip();
            if (line.isEmpty()) {
                continue;
            }

            String[] parts = line.split("=", 2);
            if (parts.length != 2) {
                throw new TaskDeserializerException("Property `%s` does not specify a value with an =");
            }

            String property = parts[0].strip().toLowerCase();
            if (property.contains("[") || property.contains("]")) {
                throw new TaskDeserializerException(
                        "Property `%s` contains illegal characters [ and ]".formatted(property));
            }
            String value = parts[1].strip().replace("\\n", "\n");
            properties.put(property, value);
        }

        Task task = switch (taskType) {
            case "todo" -> todoFromProperties(properties);
            case "deadline" -> deadlineFromProperties(properties);
            case "event" -> eventFromProperties(properties);
            default -> throw new TaskDeserializerException(
                    "Invalid task type [%s] found".formatted(taskType));
        };

        return task;
    }

    /**
     * Converts a property:value map into a {@link TodoTask}.
     *
     * @param properties The property:value map to convert.
     * @return The task based on the property:value map.
     * @throws TaskDeserializerException If certain properties required by the task
     *                                   are not present.
     */
    private static TodoTask todoFromProperties(HashMap<String, String> properties)
            throws TaskDeserializerException {
        // empty string if details not provided
        String details = properties.get("details");
        if (details == null) {
            throw new TaskDeserializerException("[todo] task requires non-empty `details` property");
        }

        TodoTask task = new TodoTask(details);

        // only set isCompleted to true if `completed = 1`
        if ("1".equals(properties.get("completed"))) {
            task.markComplete();
        }
        return task;
    }

    /**
     * Converts a property:value map into a {@link DeadlineTask}.
     *
     * @param properties The property:value map to convert.
     * @return The task based on the property:value map.
     * @throws TaskDeserializerException If certain properties required by the task
     *                                   are not present.
     */
    private static DeadlineTask deadlineFromProperties(HashMap<String, String> properties)
            throws TaskDeserializerException {
        // empty string if details not provided
        String details = properties.get("details");
        if (details == null) {
            throw new TaskDeserializerException("[deadline] task requires non-empty `details` property");
        }

        String by = properties.get("by");
        if (by == null) {
            throw new TaskDeserializerException("[deadline] task requires non-empty `by` property");
        }

        try {
            DeadlineTask task = new DeadlineTask(details, by);

            // only set isCompleted to true if `completed = 1`
            if ("1".equals(properties.get("completed"))) {
                task.markComplete();
            }
            return task;
        } catch (DateTimeParseException e) {
            throw new TaskDeserializerException(
                    "deadline.by `%s` does not match format `%s`"
                            .formatted(by, DeadlineTask.DATE_TIME_INPUT_PATTERN),
                    e);
        }
    }

    /**
     * Converts a property:value map into a {@link EventTask}.
     *
     * @param properties The property:value map to convert.
     * @return The task based on the property:value map.
     * @throws TaskDeserializerException If certain properties required by the task
     *                                   are not present.
     */
    private static EventTask eventFromProperties(HashMap<String, String> properties)
            throws TaskDeserializerException {
        // empty string if details not provided
        String details = properties.get("details");
        if (details == null) {
            throw new TaskDeserializerException("[event] task requires non-empty `details` property");
        }

        String start = properties.get("start");
        if (start == null) {
            throw new TaskDeserializerException("[event] task requires non-empty `start` property");
        }

        String end = properties.get("end");
        if (end == null) {
            throw new TaskDeserializerException("[event] task requires non-empty `end` property");
        }

        EventTask task = new EventTask(details, start, end);

        // only set isCompleted to true if `completed = 1`
        if ("1".equals(properties.get("completed"))) {
            task.markComplete();
        }
        return task;
    }
}
