package grug.command.parser;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.time.LocalDate;

import org.junit.jupiter.api.Test;

import grug.command.AddTaskCommand;
import grug.command.DeleteTaskCommand;
import grug.command.EmptyCommand;
import grug.command.FindTasksByDateCommand;
import grug.command.FindTasksByDetailsCommand;
import grug.command.ListTasksCommand;
import grug.command.MarkTaskCommand;
import grug.command.QuitCommand;
import grug.command.SetPriorityCommand;
import grug.command.UnmarkTaskCommand;
import grug.task.DeadlineTask;
import grug.task.EventTask;
import grug.task.TaskPriority;

/** Tests conversion of user input into typed commands. */
class CommandParserTest {
    @Test
    void parseInput_findOnCommand_returnsExpectedCommands() throws Exception {
        // previous year, instead of current year
        assertInstanceOf(FindTasksByDateCommand.class, CommandParser.parseInput("find-on 2025-09-09"));
        // no year, instead of current year
        assertInstanceOf(FindTasksByDateCommand.class, CommandParser.parseInput("find-on 09-09"));
    }

    @Test
    void parseInput_findCommands_returnsExpectedCommands() throws Exception {
        assertInstanceOf(FindTasksByDetailsCommand.class, CommandParser.parseInput("find a"));
        assertInstanceOf(FindTasksByDetailsCommand.class, CommandParser.parseInput("find a b"));
        assertInstanceOf(FindTasksByDetailsCommand.class, CommandParser.parseInput("find  a  b "));
    }

    @Test
    void parseInput_findCommands_parsesDetails() throws Exception {
        FindTasksByDetailsCommand findWithSpaces = assertInstanceOf(
                FindTasksByDetailsCommand.class,
                CommandParser.parseInput("find  a  b  "));
        assertEquals(findWithSpaces.detailsSubstring(), "a b");

        FindTasksByDetailsCommand findWithNewlines = assertInstanceOf(
                FindTasksByDetailsCommand.class,
                CommandParser.parseInput("\tfind a\r\nb\n"));
        assertEquals(findWithNewlines.detailsSubstring(), "a b");
    }

    // Generated by GPT-5.
    @Test
    void parseInput_blankAndSimpleCommands_returnsExpectedCommands() throws Exception {
        assertInstanceOf(EmptyCommand.class, CommandParser.parseInput("  "));
        assertInstanceOf(QuitCommand.class, CommandParser.parseInput("BYE"));
        assertInstanceOf(ListTasksCommand.class, CommandParser.parseInput("list"));
    }

    // Generated by GPT-5, modified manually.
    @Test
    void parseInput_taskCommands_parsesDetailsAndDates() throws Exception {
        AddTaskCommand todo = assertInstanceOf(AddTaskCommand.class,
                CommandParser.parseInput("todo buy milk"));
        AddTaskCommand deadline = assertInstanceOf(AddTaskCommand.class,
                CommandParser.parseInput("deadline submit /by 2026-12-25 17:00"));
        AddTaskCommand event = assertInstanceOf(AddTaskCommand.class,
                CommandParser.parseInput("event meeting /from 2026-12-25 10:00 /to 2026-12-25 11:00"));

        assertEquals("buy milk", todo.task().getDetails());

        assertInstanceOf(DeadlineTask.class, deadline.task());
        DeadlineTask deadlineTask = (DeadlineTask) deadline.task();
        assertEquals("2026-12-25 17:00", deadlineTask.getDeadlineDatetime().toString().replace('T', ' '));

        assertInstanceOf(EventTask.class, event.task());
        EventTask eventTask = (EventTask) event.task();
        assertEquals("2026-12-25 10:00", eventTask.getStartDatetime().toString().replace('T', ' '));
    }

    @Test
    void parseInput_eventTask_startAfterEndThrows() {
        assertThrows(GrugCommandParserException.class, () -> {
            CommandParser.parseInput("event throws /from 12-25 /to 12-24");
        });
        assertDoesNotThrow(() -> {
            CommandParser.parseInput("event does not throw /from 12-25 /to 12-25");
        });
    }

    // Generated by GPT-5.
    @Test
    void parseInput_indexAndDateCommands_parsesArguments() throws Exception {
        MarkTaskCommand mark = assertInstanceOf(MarkTaskCommand.class,
                CommandParser.parseInput("mark 2"));
        UnmarkTaskCommand unmark = assertInstanceOf(UnmarkTaskCommand.class,
                CommandParser.parseInput("unmark 3"));
        DeleteTaskCommand delete = assertInstanceOf(DeleteTaskCommand.class,
                CommandParser.parseInput("delete 4"));
        FindTasksByDateCommand find = assertInstanceOf(FindTasksByDateCommand.class,
                CommandParser.parseInput("find-on 2026-12-25"));

        assertEquals(2, mark.taskNum());
        assertEquals(3, unmark.taskNum());
        assertEquals(4, delete.taskNum());
        assertEquals(LocalDate.of(2026, 12, 25), find.date());
    }

    @Test
    void parseInput_setPriorityCommand_parsesTaskNumberAndPriority() throws Exception {
        SetPriorityCommand urgent = assertInstanceOf(SetPriorityCommand.class,
                CommandParser.parseInput("set-priority 2 /priority urg"));
        SetPriorityCommand highWithErraticWhitespace = assertInstanceOf(
                SetPriorityCommand.class,
                CommandParser.parseInput("  SET-PRIORITY\t4   /priority\nHiG  "));

        assertEquals(2, urgent.taskNum());
        assertEquals(TaskPriority.URGENT, urgent.newPriority());
        assertEquals(4, highWithErraticWhitespace.taskNum());
        assertEquals(TaskPriority.HIGH, highWithErraticWhitespace.newPriority());
    }

    @Test
    void parseInput_setPriorityCommandWithMissingOrInvalidPriority_throwsParserException() {
        assertThrows(GrugCommandParserException.InvalidUsage.class, () -> {
            CommandParser.parseInput("set-priority 1");
        });
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> {
            CommandParser.parseInput("set-priority 1 /priority extreme");
        });
    }

    @Test
    void parseInput_setPriorityCommandWithErraticTaskNumber_throwsParserException() {
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> {
            CommandParser.parseInput("set-priority first /priority low");
        });
        assertThrows(GrugCommandParserException.InvalidUsage.class, () -> {
            CommandParser.parseInput("set-priority 1 2 /priority low");
        });
    }

    // Generated by GPT-5.
    @Test
    void parseInput_invalidCommands_throwsDescriptiveParserException() {
        assertThrows(GrugCommandParserException.UnknownCommand.class, () -> CommandParser.parseInput("unknown"));
        assertThrows(GrugCommandParserException.InvalidUsage.class, () -> CommandParser.parseInput(
                "todo"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "mark not-a-number"));
        assertThrows(GrugCommandParserException.InvalidArgument.class, () -> CommandParser.parseInput(
                "deadline submit /by invalid-date"));
        assertThrows(GrugCommandParserException.class, () -> CommandParser.parseInput("find"));
    }
}
