package grug.storage;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import grug.task.Task;
import grug.task.TodoTask;

/** Tests persistence of tasks through {@link TaskStorage}. */
class TaskStorageTest {

    @TempDir
    Path temporaryDirectory;

    // Generated by GPT-5.
    @Test
    void getFilepath_returnsConfiguredPath() {
        Path path = temporaryDirectory.resolve("tasks.txt");

        assertEquals(path.toString(), new TaskStorage(path.toString()).getFilepath());
    }

    // Generated by GPT-5.
    @Test
    void saveAndLoadTasks_roundTripsTasks() throws Exception {
        Path path = temporaryDirectory.resolve("tasks.txt");
        TaskStorage storage = new TaskStorage(path.toString());
        TodoTask task = new TodoTask("read book");
        task.markComplete();

        storage.saveTasks(List.of(task));
        List<Task> loaded = storage.loadTasks();

        assertTrue(Files.exists(path));
        assertEquals(1, loaded.size());
        assertEquals("read book", loaded.get(0).getDetails());
        assertTrue(loaded.get(0).getCompleted());
    }
}
